name: build

on:
  push:

permissions:
  packages: write

jobs:
  build:
    name: build container image(s)
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64v8]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64v8
            platform: linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/spectrapulse/sd-n.me
          tags: |
            type=raw,value=${{ matrix.arch }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.metadata.outputs.tags }}

  merge:
    runs-on: ubuntu-20.04
    needs: [build]
    env:
      IMAGE: ghcr.io/spectrapulse/sd-n.me
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker buildx imagetools create --tag ${IMAGE}:latest ${IMAGE}:{amd64,arm64v8}
